### PR TITLE
Fix bug that caused Python service to not exit on app close

### PR DESCRIPTION
**Pull request by bitinerant**

### CODE REVIEW

**Comment by mzakharo** [comment]
I think this just disables sticky and foreground which is already stated as optional. Comma is used to list multiple services.

**Comment by mzakharo** [comment]
I think this just disables sticky and foreground which is already stated as optional. Comma is used to list multiple services.

There are 3 types of sercices:
1. No params. Exits on app close.
2. Sticky. Continues running on app close. Gets restarted on exit crash
3. Foreground + sticky. Same as sticky plus does not get restarted on memory pressure.

**Comment by bitinerant** [comment]
Agreed. I think the way it is now (`Srv:srv.py:foreground:sticky`) is a syntax error and it's unclear what is done with the text after the second colon. The example line from the programmers (`NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY`) makes the syntax clear. I tested this thoroughly on my old Android 8 phone. With `Srv:srv.py:foreground:sticky` the background Python service did not close with the app, but with `Srv:srv.py,foreground:sticky` it was closed when the app was closed.

**Comment by mzakharo** [comment]
The example you are referring to just lists 2 separate services separated by a comma. Programmers manual is incomplete and does not list how to declare foreground sticky services which run after the app is closed. It is not a bug but a feature. Some usecases wish for service to run when the app is closed to process sensor input. You dont have to declare foreground and sticky options. Then the service will exit on app close. The syntax in this manual is correct but maybe confusing.

**Comment by bitinerant** [comment]
Okay--you are correct. I think it's an odd syntax, but I finally found the documentation: [Arbitrary service scripts](https://python-for-android.readthedocs.io/en/latest/services/#arbitrary-scripts-services)

**Comment by mzakharo** [comment]
@bitinerant  ->  there was a bug where if you do not specify `sticky`  and/or `foreground`, the service gets killed when the app is in background and needs to be restarted manually. Please take a look at https://github.com/mzakharo/flutter_with_python_android/commit/b671b05e3f41b555996d9305c4b91ff1ad803458 for a solution.

**Pull request closed without merging**
